### ISSUE TITLE
2dActorTools βのバグ報告

### ISSUE THREAD

**Issue by haduki-yuki** [wabimochi/2dActorTools#13]
# 2dActorTools β

お疲れさまです。
いつも使わせてもらっており、たいへん助かっております。
使用している中でバグと思われる挙動がありましたのでご報告いたします。

### モーショングラフィックスを使った自動字幕生成で、ボイスの長さに対して字幕が1フレーム足りない状態で生成される
- 音声が150Fだとしたら字幕が149Fで生成され各字幕感に1Fずつ余白が空いている状態です。

### キャラクターの立ち絵をセットするときにタイムライン上に他のエッセンシャルグラフィックスがあると反映されない
- 手打ちで作成したエッセンシャルグラフィックスの字幕がタイムラインに存在すると、立ち絵のレイヤーをクリックしても応答せず反映ができませんでした。

### 最新版のAEでのモーショングラフィックステンプレートを使用するとtxtファイルの文字列が反映されない
- v18.4.1（AE 2021）ではtxtファイルの文字列を拾えず、v17.7（AE 2020）では拾えたことを確認しました。
- 旧バージョンでmogtrを作成すれば回避が可能でした。

### 口パクのフィードバック
いい感じです。Premiereで口パクの設定がとても楽になりました。
見ている感じではもう少しパクパクを多めにしてもらえるとより喋ってる感じが出るかなと思いました。

### その他機能についてのフィードバック
自動字幕、立ち絵設定、自動追加など非常に役立っています。Premiereでのボイロ動画の作成の時短になってます。
また、自動字幕生成時にテキストファイルがない状態だとファイルネームを拾ってもらえるのでEXvoiceも非常に役に立ってます。

**Comment by wabimochi** [comment]
ありがとうございます！
どの現象もこちらで再現しました。
回避可能なので、もしかしたら1.2.1になるかもしれませんが修正します！
