### ISSUE TITLE
「ターゲットトラックにMOGRTを並べる」が特定条件下で失敗する

### ISSUE THREAD

**Issue by szkp0151** [wabimochi/2dActorTools#14]
■現象
音声ファイル設置後、対象となるレイヤーを選択。
「ターゲットトラックにMOGRTを並べる」実行時に想定と異なる動作を行う
　・ターゲットとなるオーディオレイヤの先頭のファイルにのみテキストが適応される
　・txt内容のテキストではなくMOGRTのサンプル文章がそのまま表示される

■実施パターン
　ターゲットビデオレイヤ V1
　ターゲットオーディオレイヤA4
　　　→状況発生

　ターゲットビデオレイヤ V2
　ターゲットオーディオレイヤA4
　　　→状況発生

　ターゲットビデオレイヤ V5
　ターゲットオーディオレイヤA4
　　　→状況は発生しない(想定通り動作)

　ターゲットビデオレイヤ V6
　ターゲットオーディオレイヤA4
　　　→状況は発生しない(想定通り動作)

尚ターゲットオーディオレイヤがA4以外の場合は想定通り動作しました。
若干限られた状況下での発生となり、修正依頼というわけではありませんが共有だけさせていただきます。

**Comment by wabimochi** [comment]
ご報告ありがとうございます！

- Pr 15.4.1
- 2dactortools v1.2-beta2
- サンプルのMOGRT(https://github.com/wabimochi/2dActorTools/releases/tag/v1.0)

で試したところ再現できませんでした。
それぞれのバージョンや使用したMOGRT(自作のものであればAeのバージョンも)を教えていただけないでしょうか？

**Comment by wabimochi** [comment]
今のところこちらで再現できていないので、一度Closeさせていただきます。
また同じような現象が発生したら再度Openするか、新しいIssueで報告していただけると助かります！
