### ISSUE TITLE
立ち絵のシーケンスが配置できない

### ISSUE THREAD

**Issue by sotono-046** [wabimochi/2dActorTools#20]
立ち絵を表示させたいのですが、
動画の通りにシーケンスを作成するところまでできました。
そこからシーケンスをタイムラインに配置したいのですが、何故か配置することができません…

ちなみに、
```
シーケンスイン／アウトの範囲内にコンテンツがありません
```
というエラーメッセージ？が表示されていました。

バージョンは下記画像を参照ください。
![image](https://github.com/wabimochi/2dActorTools/assets/32998973/487747f7-cfb1-4cc7-a31c-50d1cf3a6bc1)

**Comment by wabimochi** [comment]
恐らく作成したシーケンス内にクリップが一つも無い状態になっていると思います。
なんでもいいのでクリップをシーケンスに追加した状態で再度タイムラインに配置してみてください。

**Comment by sotono-046** [comment]
出力されたシーケンスの中身はこの様になっていました。
![image](https://github.com/wabimochi/2dActorTools/assets/32998973/22a414a0-be99-4394-aece-76d4f3532503)
この状態で入れようとしても入れられなかったので、
適当な画像を追加したり置き換えてみたりしたのですが、
同様の現象が起こり、タイムラインに載せられませんでした。

エラーメッセージに関してですが、現在はどこにも出ている気配がなく、
どういった原因でTLに置けないのかが不明です。

**Comment by wabimochi** [comment]
同バージョンのPremiere Pro(Windows)で試しましたが、再現できませんでした。
シーケンスに自身のシーケンスを置こうとしている、子シーケンスに親シーケンスを置こうとしているなど、原因を思いつくことはできますが、エラーメッセージがない場合は解決策を提示するのは難しくなります…。
普通に作成したシーケンスでも同様であれば、一般的なPremiere Proのヘルプが有効かもしれません。

**Comment by sotono-046** [comment]
再現できないということで、こちらの問題かと思い色々試してみました。
結果、シーケンスを置くことに成功しました。

置きたい目的のシーケンスにフォーカスを合わせた状態で、鍵左側のV1などをターゲットにしつつ、
立ち絵シーケンスをドラッグしたら、配置することができました。
![image](https://github.com/wabimochi/2dActorTools/assets/32998973/dbb87cb9-3eb2-4f3a-a777-48d789b96b62)

また、エラーメッセージに関してですが、左上のボタンをオフにすることで表示されました。
![image](https://github.com/wabimochi/2dActorTools/assets/32998973/41d51398-2c04-40e6-8ca4-0cb769e93f44)

ありがとうございました。

**Comment by wabimochi** [comment]
みんな一度は引っかかるやつですね…。私も使い初めの頃にそれで困ったのを思い出してきました。
何にせよ、解決できたようで良かったです！
