### ISSUE TITLE
「立ち絵設定」で「サムネイル用画像の処理中」から音沙汰がなくなる

### ISSUE THREAD

**Issue by ma-f** [wabimochi/2dActorTools#3]
便利なツール、ありがとうございます。
此方で不具合報告させて頂きます。

内容
　「立ち絵設定 → 保存 → サムネイル用画像の処理中」で半日以上音沙汰なくなりました。

環境
　2dActorTools v1.0.1 + PP 14.7

備考
　PP 14.4~6も同症状でしたが、14.3.2ではスムーズにサムネ作成されました。
　開発や導入案内の参考にして頂けると幸いです。

PS.Githubに不慣れでissueを少し汚してしまいました、申し訳ありません。

**Comment by wabimochi** [comment]
詳細な動作確認ありがとうございます、とても助かります！特にフォーマット等も気にせず書いていただいて構いません。

こちらで修正されたのを確認できたので、closeしました。まだ同様の問題が発生する場合は再度openして下さい。
すぐにはzxpファイル化しないので、急ぎの場合は[未署名のエクステンションを使用する](https://github.com/wabimochi/2dActorTools#%E6%9C%AA%E7%BD%B2%E5%90%8D%E3%81%AE%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%86%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B)の方法で導入してください。
